name: CI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dev-tests:
    name: Install Dev Dependencies
    runs-on: ubuntu-latest
    container: php:8.0-cli-buster
    steps:
      # checkout code
      - name: checkout code
        uses: actions/checkout@v2
      # install wget / unzip / git which might be used for composer setup and by composer itself
      - shell: bash
        run: apt-get update && apt-get -y install --no-install-recommends wget unzip git
      # install composer
      - shell: bash
        run: chmod +x .github/scripts/install-composer.sh && .github/scripts/install-composer.sh
      # install dependencies
      - shell: bash
        run: php composer.phar install
      # run phpunit (no coverage)
      - shell: bash
        run: vendor/phpunit/phpunit/phpunit -c phpunit.xml --no-coverage
